### ISSUE TITLE
add support for definition lists (`=defn`)

### ISSUE THREAD

**Issue by uvtc** [perl6/Pod-To-HTML#15]
I think that [the Perl 6 glossary](https://doc.perl6.org/language/glossary) would look better if the IRC Lingo entries were a single definition list, but it appears that Pod-To-HTML doesn't support definition lists yet.

**Comment by tbrowder** [comment]
This seems to be a rakudo pod issue.

**Comment by JJ** [comment]
This should have been fixed by @tbrowder in one of the next Rakudo releases.

**Comment by JJ** [comment]
In principle, closed by 326838cd26be12f863ecc1504624f10da76f4857
