### ISSUE TITLE
Dealing with external POD6

### ISSUE THREAD

**Issue by JJ** [perl6/Pod-To-HTML#30]
I haven't walked through all tests, but my impression is that it's always rendering to HTML what has already turned into a pod data structure by the Perl6 interpreter. That's actually an `eval` away from any other program, but is there any other way to access that?

**Comment by zoffixznet** [comment]
> but is there any other way to access that?

Not aware of anything. Considering Pod6 configuration can be executable Perl 6 code, the current incantation of Pod6 is inherently unsafe:

```
$ cat Foo.pod6 
=begin foo :content(BEGIN say "pwned")

=end foo

$ perl6 --doc=Text Foo.pod6 
pwned
foo
```

**Comment by JJ** [comment]
Apparently there's a bit of precomp+NQP magic involved, at least [here](https://github.com/perl6/doc/blob/1a999220f3c89542a5bcbdeef3bc5c9fd3c24c91/lib/Pod/Convenience.pm6#L108-L124)

**Comment by JJ** [comment]
And in any case it does not correspond to this repo, which is actually using EVAL to do the same. I close it now.
