### ISSUE TITLE
Test errors with 2018.06

### ISSUE THREAD

**Issue by JJ** [perl6/Pod-To-HTML#43]
Which is weird, because it was working somewhere else. This is an Ubuntu 16.04 LTS

```
===SORRY!===
Function 'Pod::Defn' needs parens to avoid gobbling block (or perhaps it's a class that's not declared or available in this scope?)
at /home/jmerelo/progs/forks/perl6/Pod-To-HTML/lib/Pod/To/HTML.pm (Pod::To::HTML):147
------>         }⏏<EOL>
Missing block (apparently claimed by 'Pod::Defn')
at /home/jmerelo/progs/forks/perl6/Pod-To-HTML/lib/Pod/To/HTML.pm (Pod::To::HTML):147
------>         }⏏<EOL>

===> Testing [FAIL]: Pod::To::HTML:ver<0.3.21>
Aborting due to test failure: Pod::To::HTML:ver<0.3.21> (use --force-test to override)
```

**Comment by JJ** [comment]
I'm compiling again 2018.06. Maybe I didn't have the latest version or something...

**Comment by JJ** [comment]
Same thing. Do I need to install master?

**Comment by zoffixznet** [comment]
That class is undefined and looking at [earlier changes](https://github.com/perl6/Pod-To-HTML/commit/b4684ff6310007709c12de2947622eece31263b8) by @jonathanstowe looks like it should be named `Pod::DefnList` instead.

**Comment by JJ** [comment]
In fact, Rakudo includes Pod::Defn but the problem is that the version I have does not return that yet. Was that released?

**Comment by zoffixznet** [comment]
Ah. No, it existed in Rakudo only for 13 days.

The module should either be patched with a backcompat shim or the changes reverted entirely. It's required by p6doc and a couple of other modules, which means they're now broken.
