### ISSUE TITLE
Make TOC inclusion optional

### ISSUE THREAD

**Issue by uzluisf** [perl6/Pod-To-HTML#62]
Right now, a table of content is always included in the output HTML. Although it could possibly be hidden using CSS (?), I think a better strategy is to include it conditionally.

I got something working on my local copy of the module but I'm afraid it might be too simplistic:
```
sub pod2html(
    ...    
    :$toc = False,
    ...
) { ... }

return $main-tm.render(
        ...
        :toc( $toc ?? do-toc($pod) !! Nil ),
        ...
) { ... }
```

**Comment by JJ** [comment]
Good idea! We'll see what can be done.

**Comment by uzluisf** [comment]
I wish I had realized this sooner but `Pod::To::HTML` supplying the Mustache renderer with the `toc` template variable is the most sane option; thus no need to make toc inclusion optional via a routine (e.g., `render`). It's only a matter of using another Mustache template that doesn't use the `toc` template variable.
