### ISSUE TITLE
Runaway mem hog

### ISSUE THREAD

**Issue by jdv** [perl6/Pod-To-HTML#7]
I see this happen on t/02-code.t and then installing without testing
it happens again with p6-doc/htmlify.p6 on lib/Language/operators.pod.

[jdv@wieldy p6-doc]$ perl6 -v
This is perl6 version 2015.04-261-g3301ec4 built on MoarVM version 2015.04-122-gead50fd
[jdv@wieldy p6-doc]$

**Comment by paultcochrane** [comment]
On 15 May 2015 6:46:03 am GMT+02:00, Justin DeVuyst <notifications@github.com> wrote:
>I see this happen on t/02-code.t and then installing without testing
>it happens again with p6-doc/htmlify.p6 on lib/Language/operators.pod.
>
>[jdv@wieldy p6-doc]$ perl6 -v
>This is perl6 version 2015.04-261-g3301ec4 built on MoarVM version
>2015.04-122-gead50fd
>[jdv@wieldy p6-doc]$
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/perl6/Pod-To-HTML/issues/7

I've done some debugging on this issue over the last few days and have found that the `visit` sub calls itself recursively while processing a POD structure and doesn't hit bottom anymore. This is after the change to Rakudo where Nil and Empty got new behaviour (IIRC Nil can no longer be used in iterations, one should now use Empty for this purpose). Unfortunately haven't had the time to investigate this further so this is all the info I have at present. Hope it helps a bit though.

**Comment by andreoss** [comment]
Adding a check for Nil value seemed to resolve it.
